### ISSUE TITLE
nopassword parameter is documented, but not supported by the module

### ISSUE THREAD

**Issue by darac** [JonEllis/ansible-sudoers#1]
The documentation for this module mentions a `nopassword` parameter, but when attempting to use it, ansible (version 2.9.18) complains:
```
fatal: [Hostname]: FAILED! => changed=false
  msg: 'Unsupported parameters for (jonellis.sudoers.sudoers) module: nopassword Supported parameters include: command, group, name, state, user'
```

I think the root cause of this is that `nopassword` is not mentioned in the `argument_spec` dictionary passed to `AnsibleModule()`.

**Comment by JonEllis** [comment]
Thanks for taking the time to create this issue.
You are exactly correct.
It looks like I failed to implement it correctly too.
It's not a feature that I use myself, but now I have implemented it and tested that it works (on Ubuntu at least).
I have pushed version 0.1.7 to galaxy.ansible.com, and pushed the code here too.

Let me know how you get on.

**Comment by JonEllis** [comment]
I believe this is fixed now, so I'll close the issue.
Feel free to open it again if you find problems with it.
